export const ErrorName = {
    BAD_GATEWAY: "BAD GATEWAY",
    BAD_REQUEST: "BAD REQUEST",
    CUSTOM_ERROR: "CUSTOM ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
    NOT_FOUND: "NOT FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
};
